In [1]:
import numpy as np

In [2]:
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5,"sudh" , 4+8j])

array(['1', '2', '3', '4', '5', 'sudh', '(4+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [8]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\argha\AppData\Local\Temp\ipykernel_11924\1655787997.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [10]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [11]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [12]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
arr = np.array([(1,2,3) , (4,5,6)],dtype = [("a",'<i2'), ("b",'<i4'), ("c",'<i8')])

In [14]:
arr

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [15]:
arr[0][0]

1

In [16]:
type(arr[0][0])

numpy.int16

In [17]:
arr[0][1]

2

In [18]:
type(arr[0][1])

numpy.int32

In [19]:
arr[0][2]

3

In [20]:
type(arr[0][2])

numpy.int64

In [21]:
arr  = np.array([[1,3],[3,4]])

In [22]:
arr

array([[1, 3],
       [3, 4]])

In [23]:
type(arr[0][1])

numpy.int32

In [24]:
mat = np.matrix(arr)

In [25]:
mat

matrix([[1, 3],
        [3, 4]])

In [26]:
l = [3,4,5,76,7]

In [27]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [28]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [29]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [30]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [31]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [32]:
issubclass(np.matrix,np.ndarray )

True

In [33]:
issubclass(np.ndarray,np.matrix )

False

In [34]:
arr

array([[1, 3],
       [3, 4]])

In [35]:
a= arr

In [36]:
b = np.copy(arr)

In [37]:
arr[0][0] = 67

In [38]:
arr

array([[67,  3],
       [ 3,  4]])

In [39]:
a

array([[67,  3],
       [ 3,  4]])

In [40]:
b

array([[1, 3],
       [3, 4]])

In [41]:
arr[-1]

array([3, 4])

In [42]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [43]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [44]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [45]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [46]:
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [47]:
np.fromfunction(lambda i , j :i/j,(3,3))

C:\Users\argha\AppData\Local\Temp\ipykernel_11924\2281161872.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\argha\AppData\Local\Temp\ipykernel_11924\2281161872.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [48]:
0/0

ZeroDivisionError: division by zero

In [ ]:
1/0

In [49]:
gen = (i*i for i in range(5))

In [50]:
def test(x):
    yield x 

In [51]:
test(5)

<generator object test at 0x000002460A981DD0>

In [52]:
gen
for i in gen :
    print(i)

0
1
4
9
16


In [53]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [54]:
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [55]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [56]:
l = [3,4,5,6,7,8]

In [57]:
arr = np.array(l)

In [58]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [59]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [60]:
type(arr)

numpy.ndarray

In [61]:
arr1.ndim

2

In [62]:
arr1.size

12

In [63]:
arr1.shape


(3, 4)

In [64]:
arr1.dtype

dtype('int32')

In [65]:
arr

array([3, 4, 5, 6, 7, 8])

In [66]:
arr.size

6

In [67]:
arr.ndim

1

In [68]:
arr.shape

(6,)

In [69]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [70]:
arr2


array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [71]:
arr2.size

16

In [72]:
arr2.ndim

3

In [73]:
arr2.shape

(2, 2, 4)

In [74]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [75]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [76]:
arr4.ndim

4

In [77]:
arr4.shape

(1, 4, 2, 4)

In [80]:
list(range(9,6.6,-.3))

TypeError: 'float' object cannot be interpreted as an integer

In [81]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [82]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [92]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [95]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [96]:
np.ones(4)

array([1., 1., 1., 1.])

In [97]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [98]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [99]:
np.empty((3,4))

array([[1.23506385e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.10343781e-312, 7.87634736e-071, 5.02911335e-037,
        1.58901103e-047],
       [9.39801455e+165, 2.37858368e+184, 1.42024857e+161,
        3.14058565e-032]])

In [103]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [105]:
np.logspace([2],[3] , axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [106]:
d = np.linspace(4,7,40)

In [107]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [108]:
d.ndim

1

In [109]:
d.shape

(40,)

In [110]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [111]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [113]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [114]:
np.random.rand(3)

array([0.60794123, 0.50457952, 0.60629354])

In [115]:
np.random.randn(5)

array([ 0.43338925,  0.03390117, -0.72716984,  1.55325696,  0.8381165 ])

In [116]:
np.random.randn(2,2,3)

array([[[-0.11389927,  1.52092118, -0.66046859],
        [ 0.44177554,  0.346984  , -0.49259685]],

       [[ 1.10685059, -1.46850625, -1.48836711],
        [-1.57312564,  1.77340629, -0.49627735]]])

In [117]:
np.random.randint(5,60, (4,4))

array([[49, 15, 27, 41],
       [20, 33,  7, 17],
       [ 7, 41, 22,  9],
       [56, 58, 41, 31]])

In [118]:
np.random.randn(2,2,3)

array([[[-0.96159711,  1.26765728,  1.50535049],
        [-0.26259319,  0.19828312,  0.13514823]],

       [[ 1.05620329,  0.90580694, -1.52675229],
        [ 0.19115204, -1.15477596,  0.67258402]]])

In [119]:
arr = np.random.randint(3,9, ( 3,3))

In [120]:
arr

array([[3, 6, 7],
       [8, 5, 6],
       [6, 5, 4]])

In [121]:
arr.reshape(1,9)

array([[3, 6, 7, 8, 5, 6, 6, 5, 4]])

In [122]:
arr.reshape(9,1)

array([[3],
       [6],
       [7],
       [8],
       [5],
       [6],
       [6],
       [5],
       [4]])

In [123]:
arr.reshape(1,1,9)

array([[[3, 6, 7, 8, 5, 6, 6, 5, 4]]])

In [124]:
arr.reshape(3,3,1)

array([[[3],
        [6],
        [7]],

       [[8],
        [5],
        [6]],

       [[6],
        [5],
        [4]]])

In [125]:
arr.reshape(3,-198979)

array([[3, 6, 7],
       [8, 5, 6],
       [6, 5, 4]])

In [126]:
arr.reshape(1,-145654656)

array([[3, 6, 7, 8, 5, 6, 6, 5, 4]])

In [127]:
arr

array([[3, 6, 7],
       [8, 5, 6],
       [6, 5, 4]])

In [128]:
arr.max()

8

In [129]:
arr.min()

3

In [130]:
arr = np.random.randint(4,100, (5,5))

In [131]:
arr

array([[84, 73, 16, 86, 17],
       [62, 95, 13, 59, 74],
       [11, 92, 67, 72, 53],
       [21, 62, 74, 30, 87],
       [21, 46,  4, 57, 65]])

In [132]:
arr[3: , 3:]

array([[30, 87],
       [57, 65]])

In [133]:
arr[:,[1,3]]

array([[73, 86],
       [95, 59],
       [92, 72],
       [62, 30],
       [46, 57]])

In [134]:
arr

array([[84, 73, 16, 86, 17],
       [62, 95, 13, 59, 74],
       [11, 92, 67, 72, 53],
       [21, 62, 74, 30, 87],
       [21, 46,  4, 57, 65]])

In [137]:
arr[arr>10]

array([84, 73, 16, 86, 17, 62, 95, 13, 59, 74, 11, 92, 67, 72, 53, 21, 62,
       74, 30, 87, 21, 46, 57, 65])

In [138]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [139]:
arr

array([[84, 73, 16, 86, 17],
       [62, 95, 13, 59, 74],
       [11, 92, 67, 72, 53],
       [21, 62, 74, 30, 87],
       [21, 46,  4, 57, 65]])

In [140]:
arr * arr

array([[7056, 5329,  256, 7396,  289],
       [3844, 9025,  169, 3481, 5476],
       [ 121, 8464, 4489, 5184, 2809],
       [ 441, 3844, 5476,  900, 7569],
       [ 441, 2116,   16, 3249, 4225]])

In [141]:
arr1 = np.random.randint(2,4,(3,3))

In [142]:
arr2 = np.random.randint(2,4,(3,3))

In [143]:
arr1

array([[3, 2, 2],
       [2, 3, 2],
       [3, 2, 2]])

In [144]:
arr2

array([[3, 2, 3],
       [3, 3, 3],
       [2, 2, 2]])

In [145]:
arr1*arr2

array([[9, 4, 6],
       [6, 9, 6],
       [6, 4, 4]])

In [147]:
arr1@arr2  #matrix multiplication

array([[19, 16, 19],
       [19, 17, 19],
       [19, 16, 19]])

In [148]:
arr/0

C:\Users\argha\AppData\Local\Temp\ipykernel_11924\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [149]:
arr**2

array([[7056, 5329,  256, 7396,  289],
       [3844, 9025,  169, 3481, 5476],
       [ 121, 8464, 4489, 5184, 2809],
       [ 441, 3844, 5476,  900, 7569],
       [ 441, 2116,   16, 3249, 4225]], dtype=int32)

In [150]:
arr = np.zeros((3,4))

In [151]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
a = np.array([1,2,3,5])

In [153]:
a


array([1, 2, 3, 5])

In [154]:
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [155]:
arr+ 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [156]:
b = np.array([5,6,7])

In [157]:
b

array([5, 6, 7])

In [158]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [159]:
b

array([5, 6, 7])

In [160]:
b = np.array([[5,6,7]])

In [161]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [162]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [163]:
arr = np.random.rand(5,4)

In [164]:
arr

array([[0.66075204, 0.02244532, 0.0549997 , 0.08613309],
       [0.58187522, 0.8641792 , 0.36924965, 0.13310243],
       [0.15029774, 0.767451  , 0.77267822, 0.96254159],
       [0.08451302, 0.9537568 , 0.1843787 , 0.8646019 ],
       [0.03169326, 0.4134255 , 0.78899364, 0.54257621]])

In [165]:
np.sqrt(arr)

array([[0.81286655, 0.14981764, 0.23452015, 0.29348439],
       [0.76280746, 0.92961239, 0.60765915, 0.36483205],
       [0.38768252, 0.87604281, 0.87902117, 0.98109204],
       [0.29071123, 0.97660473, 0.42939341, 0.92983972],
       [0.17802601, 0.64298173, 0.88825314, 0.73659773]])

In [166]:
np.exp(arr)

array([[1.93624792, 1.02269912, 1.0565403 , 1.08995138],
       [1.78939079, 2.37305749, 1.44664871, 1.142367  ],
       [1.16218022, 2.15426802, 2.16555834, 2.61834277],
       [1.08818701, 2.59544192, 1.20247112, 2.37406079],
       [1.03220084, 1.51198824, 2.20118014, 1.72043336]])

In [167]:
np.log10(arr)

array([[-0.17996149, -1.64887412, -1.25963968, -1.06482999],
       [-0.23517014, -0.06339619, -0.43267991, -0.87581403],
       [-0.82304756, -0.11494934, -0.11200133, -0.0165805 ],
       [-1.07307639, -0.02056235, -0.73428924, -0.06318381],
       [-1.49903309, -0.38360274, -0.1029265 , -0.26553925]])

In [168]:
arr1 = np.random.randint(2,5, (5,5))

In [169]:
arr1

array([[4, 4, 2, 4, 4],
       [2, 3, 3, 3, 3],
       [4, 3, 4, 4, 2],
       [4, 3, 2, 4, 2],
       [3, 2, 2, 3, 2]])

In [170]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.30103   , 0.60205999, 0.60205999],
       [0.30103   , 0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.60205999, 0.30103   ],
       [0.60205999, 0.47712125, 0.30103   , 0.60205999, 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.47712125, 0.30103   ]])

In [171]:
np.random.seed(13)

In [174]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])